### PR TITLE
Export ConsoleFormat class

### PR DESCRIPTION
**Pull request by xamgore**
If a user wants to change the formatting a bit, he has to completely
redefine (copy-paste) the current implementation. Though, he could
just inherit the ConsoleFormat class and override some of the methods or fields.

### CODE REVIEW

**Comment by xamgore** [comment]
@duccio It would be nice if you could publish a new version after merging PR :)

**Comment by TroyDota** [comment]
why wasnt this merged 👎

**Comment by TroyDota** [comment]
holy shit i didnt think it would get instantly merged 🥇 PogU

**Comment by duccio** [comment]
Thanks @TroyDota for your reminder 😉 I just published a new version on NPM with this PR and a totally updated dependencies...

Sometimes open-source maintainer "need" to hear from people that are using their projects.

Thanks again.

**Comment by TroyKomodo** [comment]
<3

**Comment by xamgore** [comment]
Thank you very much! 👍

**Pull request merged**
